[package]
name = "amnis"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
async-stream = "0.3"
bytes = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
pin-project-lite = "0.2"
